FROM httpd
SHELL ["bash", "-c"]
RUN apt update && apt install -y openssl
COPY . .
ENV digest_user joi
ENV digest_realm reaml
ENV digest_password false
RUN digest="$(printf "%s:%s:%s" "$digest_user" "$digest_realm" "$digest_password" | md5sum | awk '{print $1}')" \
 && printf "%s:%s:%s\n" "$user" "$realm" "$digest" | tee -a "/usr/local/apache2/passwd.digest"
RUN rm -fr htdocs && ln -sfn public htdocs \
 && . ssl-keygen \
 && openssl dhparam 2048 > tls/dhparam.pem \
 && cp httpd.conf conf/httpd.conf
EXPOSE 443 80
