FROM httpd
SHELL ["bash", "-c"]
RUN apt update && apt install -y openssl
COPY . .
ENV digest_user joi
ENV digest_realm realm
ENV digest_password false
RUN digest="$(printf "%s:%s:%s" "$digest_user" "$digest_realm" "$digest_password" | md5sum | awk '{print $1}')" \
 && printf "%s:%s:%s\n" "$digest_user" "$digest_realm" "$digest" | tee -a "passwd.digest" \
# && echo joi:$(echo -n 'joi:false' | base64) | tee -a passwd.basic
 && echo joi:$(openssl passwd -apr1 false) | tee -a passwd.basic
RUN rm -fr htdocs && ln -sfn public htdocs \
 && . ssl-keygen \
 && cp httpd.conf conf/httpd.conf
EXPOSE 443 80
