#!/bin/bash -eu

##
## with Docker
##

iCommon() {
  apt update
  DEBIAN_FRONTEND=noninteractive apt install -y tzdata
  apt install -y curl git vim
}

iDocker() {
  apt install -y software-properties-common
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  apt install -y docker-ce
}

iNginx() {
  apt install -y nginx nginx-extras
  nginx -v
  /etc/init.d/nginx start
}

iPhp() {
  apt install -y $(apt search php | grep "^php7" | grep -v snmp | grep -v fpm | awk -F'/' '{print $1}' | xargs)
  php -v
}

iPhpWeb() {
  iPhp
  iNginx
  apt install -y $(apt search php | grep "^php7" | grep -v snmp | grep fpm | awk -F'/' '{print $1}' | xargs)
  /usr/sbin/php-fpm7* -v
  /etc/init.d/php7*-fpm start
}

iNodejs() {
  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
  . ~/.bashrc
  LATEST=$(nvm ls-remote | grep 'Latest LTS' | tail -1 | awk '{print $1}')
  nvm install $LATEST
  nvm alias default $LATEST
  nvm use $LATEST
  node --version
  npm --version
}

iNodejsWeb() {
  iNodejs
  iWeb
  apt install -y supervisor
  /etc/init.d/supervisor start
}

iBuild() {
  apt install -y g++ make libssl-dev libreadline-dev zlib1g-dev libffi-dev
}

iLatest() {
  LATEST=$($1 install --list | grep -v '[A-Za-z]' | tail -1)
  $1 install $LATEST
  $1 global $LATEST
  $2 --version
}

iPython() {
  iBuild
  git clone --depth=1 https://github.com/yyuu/pyenv.git ~/.pyenv
  echo 'export PYENV_ROOT="$HOME/.pyenv"' | tee -a ~/.bashrc
  echo 'export PATH="$PATH:$PYENV_ROOT/bin"' | tee -a ~/.bashrc
  echo 'eval "$(pyenv init -)"' | tee -a ~/.bashrc
  . ~/.bashrc
  iLatest pyenv python
  pip --version
}

iPythonWeb() {
  iPython
  iNginx
  pip install gunicorn
  gunicorn --version
  pip install django
  django-admin --version
}

iRuby() {
  iBuild
  git clone --depth=1 https://github.com/sstephenson/rbenv.git ~/.rbenv
  git clone --depth=1 https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
  echo 'export PATH="$PATH:$HOME/.rbenv/bin"' | tee -a ~/.bashrc
  echo 'eval "$(rbenv init -)"' | tee -a ~/.bashrc
  . ~/.bashrc
  iLatest rbenv ruby
  bundle --version
  gem install unicorn
  unicorn --version
}

iRubyWeb() {
  iRuby
  iNginx
  pip install gunicorn
  gunicorn --version
}

iJava() {
  apt install -y openjdk-8-jdk-headless openjdk-8-jre-headless
}

main() {
    date +'START    my-init %Y-%m-%d %H:%M:%S'
    iCommon
    for cmd in $@
    do
      $cmd
    done
    if [[ "$@" == '' ]]
    then
      echo 'usage: $0 [support]'
      echo '  support'
      echo '    iNginx'
      echo '    iPhp'
      echo '    iPhpWeb'
      echo '    iNodejs'
      echo '    iNodejsWeb'
      echo '    iPython'
      echo '    iPythonWeb'
      echo '    iRuby'
      echo '    iRubyWeb'
      echo '    iJava'
    fi
    date +'FINISHED my-init %Y-%m-%d %H:%M:%S'
}

main $@ | tee -a /var/log/cloud-my-inst.log

