#!/bin/bash -eu

. inst iNginx

git clone https://github.com/jobscale/_.git projects/_
git clone https://github.com/jobscale/web.git

rm -fr /etc/nginx/sites-*
rm -fr /etc/nginx/conf.d
ln -sfn /var/site/projects/_/etc/nginx/conf.d /etc/nginx/conf.d
