#!/bin/bash -eu

directory=tls
country=JA
state=Osaka
locality=Osaka
organizational=jsx.jp
unit=Developpers
common=*.jsx.jp
fname=wildcard.jsx.jp
days=3655

rsa() {
  openssl genrsa \
    -out $directory/client.key 4096
  openssl req \
    -new \
    -subj "/C=$country/ST=$state/L=$locality/O=$organizational/CN=$common" \
    -key $directory/client.key \
    -out $directory/client.csr
  openssl x509 \
    -req \
    -days 365 \
    -in $directory/client.csr \
    -CA $directory/$fname.cert \
    -CAkey $directory/$fname.key \
    -set_serial 01 \
    -out $directory/client.crt
}

rsa
