#!/bin/bash -eu

directory=conf
country=JA
state=Osaka
locality=Osaka
organizational=jsx.jp
unit=Developpers
common=*.jsx.jp
fname=server
days=3655

random() {
  head -c 8 /dev/random | od -x -An | sed -e 's/ //g' | tee ~/.rnd
}

rsa() {
  openssl req \
    -new \
    -newkey rsa:4096 \
    -days $days \
    -nodes \
    -x509 \
    -subj "/C=$country/ST=$state/L=$locality/O=$organizational/CN=$common" \
    -keyout $directory/$fname.key \
    -out $directory/$fname.crt
}

random
rsa
